apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.component_id | dump}}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
  annotations:
    argocd/app-name: ${{values.repo_name}}
    github.com/project-slug: ${{values.destination }}
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-id: ${{values.component_id}}
  tags:
    - java
    - quarkus
  links:
    - url: https://devspaces${{ values.cluster }}/#https://github.com/${{values.destination}}?che-editor=che-incubator/che-code/insiders&devfilePath=.devfile-vscode.yaml
      title: CodeReady Workspaces (VS Code)
      icon: web
    - url: https://devspaces${{ values.cluster }}/#https://github.com/${{values.destination}}?che-editor=che-incubator/che-idea/next&devfilePath=.devfile-intellij.yaml
      title: CodeReady Workspaces (JetBrains IntelliJ)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: ${{values.owner | dump}}