apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{values.repo_name | dump}}
spec:
  destination:
    namespace: ${{ values.namespace }}
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/base
    repoURL: https://github.com/${{ values.org }}/${{values.repo_name | dump}}
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
