apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: techdocs-template
  title: Create a techdocs sample
  description: Create a techdocs sample
  tags:
    - documentation
    - techdocs
spec:
  owner: janus-authors
  system: janus-idp
  type: service

  parameters:
    - title: Provide information about the existing component
      required:
        - orgName
        - repoName
        - componentName
      properties:
        orgName:
          title: Organization Name
          type: string
        repoName:
          title: Repository Name
          type: string
        componentName:
          title: Component Name
          type: string
          description: Attach the techdocs to an existing component
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind:
                - Component
    - title: Provide information about the new component
      required:
        - owner
        - system
      properties:
        owner:
          title: Owner
          type: string
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind:
                - Group
                - User
        system:
          title: System
          type: string
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind:
                - System

  steps:
    - id: sourceCodeTemplate
      name: Generating the Source Code Component
      action: fetch:template
      input:
        url: ./skeleton
        copyWithoutTemplating:
          - .github/workflows/
        values:
          orgName: ${{ parameters.orgName }}
          repoName: ${{ parameters.repoName }}-techdocs
          owner: ${{ parameters.owner }}
          system: ${{ parameters.system }}
          applicationType: documentation
          description: Contains the techdocs for ${{ parameters.repoName }}
          sourceControl: github.com

    - id: catalogTemplate
      name: Generating the Catalog Info Component
      action: fetch:template
      input:
        url: ../../../skeletons/catalog-info/
        values:
          # Gitops specific values
          partOf: ${{ parameters.componentName }}

          orgName: ${{ parameters.orgName }}
          repoName: ${{ parameters.repoName }}-techdocs
          owner: ${{ parameters.owner }}
          system: ${{ parameters.system }}
          applicationType: documentation
          description: Contains the techdocs for ${{ parameters.repoName }}
          sourceControl: github.com

    - id: publish
      name: Publishing to the Source Code Repository
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: Contains the techdocs for ${{ parameters.repoName }}
        repoUrl: github.com?owner=${{ parameters.orgName }}&repo=${{ parameters.repoName }}-techdocs
        defaultBranch: main

    - id: register
      name: Registering the Catalog Info Component
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml

  output:
    links:
      - title: Open the Source Code Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open the Catalog Info Component
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
