apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: dotnet-frontend-template
  title: Create a .NET Frontend application with a CI pipeline
  description: Create a starter .NET frontend application with a CI pipeline
  tags:
    - recommended
    - dotnet
spec:
  owner: janus-authors
  system: janus-idp
  type: service

  parameters:
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - dev.azure.com

    - title: Provide information about the new component
      required:
        - owner
        - system
        - port
      properties:
        title:
          title: Title
          type: string
          description: The title of the component
        description:
          title: Description
          type: string
          description: Help others understand what this component is for
        owner:
          title: Owner
          type: string
          description: The owner of the component
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind:
                - Group
                - User
        system:
          title: System
          type: string
          description: The system that the component belongs to
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind:
                - System
        port:
          title: Port
          type: number
          default: 5000
          description: Override the port exposed for the application

  steps:
    - id: sourceCodeTemplate
      name: Generating the Source Code Component
      action: fetch:template
      input:
        url: ./skeleton
        values:
          orgName: ${{ parameters.orgName }}
          repoName: ''
          owner: ${{ parameters.owner }}
          system: ${{ parameters.system }}
          title: ${{ parameters.title }}
          description: ${{ parameters.description }}
          port: ${{ parameters.port }}
          applicationType: website
          sourceControl: dev.azure.com

    - id: catalogTemplate
      name: Generating the Catalog Info Component
      action: fetch:template
      input:
        url: ../../skeletons/catalog-info/
        values:
          orgName: ${{ parameters.repoUrl }}
          repoName: ''
          owner: ${{ parameters.owner }}
          system: ${{ parameters.system }}
          title: ${{ parameters.title }}
          description: ${{ parameters.description }}
          port: ${{ parameters.port }}
          applicationType: website
          sourceControl: dev.azure.com

    - id: publish
      name: Publishing to the Source Code Repository
      action: publish:azure
      input:
        allowedHosts: ['dev.azure.com']
        description: ${{ parameters.description }}
        repoUrl: ${{ parameters.repoUrl }}
        defaultBranch: main

    - id: register
      name: Registering the Catalog Info Component
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml

  output:
    links:
      - title: Open the Source Code Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open the Catalog Info Component
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
