apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: argocd-template
  title: Add ArgoCD to an existing project
  description: Add ArgoCD to an existing project
  tags:
    - recommended
    - argocd
spec:
  owner: janus-authors
  type: service

  parameters:
    - title: Provide information about the existing GitHub location
      required:
        - githubOrg
        - repoName
      properties:
        githubOrg:
          title: GitHub Organization
          type: string
        repoName:
          title: Repository Name
          type: string
    - title: Provide information about the existing component
      required:
        - port
      properties:
        port:
          title: Port
          type: number
          description: The port exposed for the application
    - title: Provide information about the new component
      required:
        - owner
        - system
      properties:
        owner:
          title: Owner
          type: string
          description: Owner of the component
          default: janus-authors
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              - Group
              - User
        system:
          title: System
          type: string
          description: System of the component
          default: examples
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              - System
    - title: Provide information about the ArgoCD deployment
      required:
        - useArgocd
      properties:
        useArgocd:
          title: Include ArgoCD
          type: boolean
          default: true
          ui:widget: radio
          description: Should the component include a ArgoCD workflow
      dependencies:
        useArgocd:
          oneOf:
            - properties:
                useArgocd:
                  const: true
                imageRepository:
                  title: Select a registry
                  type: string
                  default: quay.io
                  enum:
                    - image-registry.openshift-image-registry.svc:5000
                    - quay.io
                  enumNames:
                    - Internal OpenShift Registry
                    - Quay
                imageUrl:
                  title: Image URL
                  type: string
                  description: Enter the Quay.io or OpenShift Image URL <REGISTRY>/<IMAGE_URL>/<REPO_NAME>
                namespace:
                  title: Namespace
                  type: string
                  default: janus-idp
                  description: The namespace for deploying resources
              required:
                - imageRepository
                - namespace
                - imageUrl
  steps:
    - id: catalog-template
      name: Generating catalog-info.yaml
      action: fetch:template
      input:
        url: ../../scaffolder-skeletons/catalog-info-skeleton/
        values:
          # Gitops specific values
          applicationKind: Resource
          dependsOn: ${{ parameters.repoName }}

          # Normal values
          githubOrg: ${{ parameters.githubOrg }}
          repoName: ${{ parameters.repoName }}-gitops
          owner: ${{ parameters.owner }}
          system: ${{ parameters.system }}
          applicationType: gitops
          description: Contains the ArgoCD manifests for ${{ parameters.repoName }}
          namespace: ${{ parameters.namespace }}
          imageUrl: ${{ parameters.imageUrl }}
          imageRepository: ${{ parameters.imageRepository }}
          port: ${{ parameters.port }}

    - id: manifests-template
      name: Generating manifests component
      action: fetch:template
      input:
        url: ../../scaffolder-skeletons/manifests-skeleton/
        values:
          githubOrg: ${{ parameters.githubOrg }}
          repoName: ${{ parameters.repoName }}
          owner: ${{ parameters.owner }}
          system: ${{ parameters.system }}
          applicationType: gitops
          description: Contains the ArgoCD manifests for ${{ parameters.repoName }}
          namespace: ${{ parameters.namespace }}
          imageUrl: ${{ parameters.imageUrl }}
          imageRepository: ${{ parameters.imageRepository }}
          port: ${{ parameters.port }}

    - id: publish
      name: Publishing to Source Code Repository
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: ${{ parameters.description }}
        repoUrl: github.com?owner=${{ parameters.githubOrg }}&repo=${{ parameters.repoName }}-gitops
        defaultBranch: main

    - id: register
      name: Registering the component
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml

    - id: createArgocdResources
      name: Create ArgoCD Resources
      action: argocd:create-resources
      input:
        appName: ${{ parameters.repoName }}
        # Hardcoded value because this is kept as a secret on the server to allow forks to easily change the value
        argoInstance: argocd.operate-first.cloud
        namespace: ${{ parameters.namespace }}
        repoUrl: ${{ steps.publish.output.remoteUrl }}
        labelValue: ${{ parameters.repoName }}
        path: manifests/base

  output:
    links:
      - title: Source Code Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open Component in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
