apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: collection-template
  title: Create Ansible Collection Project
  description: Create a new starter collection Git project preconfigured with best practices.
  tags:
    - recommended
    - ansible
    - collection
spec:
  owner: ansible-authors
  system: ansible
  type: service
  parameters:
    - title: Provide information about the new component
      required:
        - repoOwner
        - repoName
        - owner
        - collectionGroup
        - collectionName
      properties:
        repoOwner:
          title: Source code repository organization name or username
          type: string
          description: The organization name or username of your source code repository. For example, “my-github-username”.
        repoName:
          title: Collection repository name
          description: The name of the new collection project repository. For example, “my-new-collection-repo”.
          type: string
        description:
          title: Collection description
          type: string
          description: Describe the collection and its purpose to help other users understand what to use it for.
        collectionGroup:
          title: Collection namespace
          description: The new collection project's namespace. For example, “my-new-collection-namespace”.
          type: string
        collectionName:
          title: Collection name
          description: The new collection project's name. For example, “my-new-collection-name”.
          type: string
        owner:
          title: Catalog Owner name
          type: string
          description: The Red Hat Developer Hub catalog item owner. This will appear on the “My items” tab. For example, “my-devhub-username”.
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind:
                - Group
                - User
        system:
          title: System
          type: string
          description: The Red Hat Developer Hub system catalog item name. This will appear on the “My items” tab. For example, “my-devhub-system”.
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind:
                - System
  steps:
    - id: ansible
      name: Generating the Ansible Source Code Component
      action: ansible:content:create
      input:
        repoOwner: '${{ parameters.repoOwner }}'
        repoName: '${{ parameters.repoName }}'
        description: '${{ parameters.description }}'
        collectionGroup: '${{ parameters.collectionGroup }}'
        collectionName: '${{ parameters.collectionName }}'
        applicationType: collection-project
        sourceControl: github.com

    - id: catalogTemplate
      name: Generating the Catalog Info Component
      action: fetch:template
      input:
        url: ../../../skeletons/catalog-info/
        values:
          repoUrl: ${{ steps.ansible.output.repoUrl }}
          owner: ${{ parameters.owner }}
          system: ${{ parameters.system }}
          applicationType: collection-project
          description: ${{ parameters.description }}
          collectionGroup: ${{ parameters.collectionGroup }}
          collectionName: ${{ parameters.collectionName }}
          sourceControl: github.com
          devSpacesBaseUrl: ${{ steps.ansible.output.devSpacesBaseUrl }}

    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts:
          - github.com
        description: ${{ parameters.description }}
        repoUrl: ${{ steps.ansible.output.repoUrl }}
        repoVisibility: 'public'
        defaultBranch: main

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}

      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
