apiVersion: backstage.io/v1alpha1
{%- if values.entityKind %}
kind: ${{ values.entityKind }}
{%- else %}
kind: Component
{%- endif %}
metadata:
  name: ${{ values.collectionGroup }}.${{ values.collectionName }}
  {%- if values.title %}
  title: ${{ values.title }}
  {%- endif %}
  {%- if values.description %}
  description: ${{ values.description }}
  {%- endif %}
  tags:
    - ansible
    - collection
  annotations:
    backstage.io/techdocs-ref: dir:.
    {%- if values.sourceControl == "gitlab.com" %}
    gitlab.com/project-slug: ${{ values.repoUrl | projectSlug }}
    {%- elif values.sourceControl == "github.com" %}
    github.com/project-slug: ${{ values.repoUrl | projectSlug }}
    {%- elif values.sourceControl == "dev.azure.com" %}
    dev.azure.com/project-repo: ${{ values.repoUrl | projectSlug }}
    {%- endif %}
  {%- if values.devSpacesBaseUrl %}
  links:
    - url: ${{ values.devSpacesBaseUrl }}${{ values.repoUrl.split("=")[1].split("&")[0] }}/${{ values.repoUrl.split("=")|last}}
      title: OpenShift Dev Spaces
      icon: web
  {%- endif %}
spec:
  type: ${{ values.applicationType }}
  {%- if values.system %}
  system: ${{ values.system }}
  {%- endif %}
  {%- if values.lifecycle %}
  lifecycle: ${{ values.lifecycle }}
  {%- else %}
  lifecycle: production
  {%- endif %}
  owner: ${{ values.owner }}
  {%- if values.dependsOn %}
  dependsOn:
    - ${{ values.dependsOn }}
  {%- endif %}
  {%- if values.partOf %}
  partOf:
    - ${{ values.partOf }}
  {%- endif %}
