apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: launch-ansible-job-template
  title: Ansible Job
  description: Launch an Ansible Job within Ansible Automation Platform
  tags:
    - recommended
    - aap
spec:
  owner: janus-authors
  system: janus-idp
  type: service
  parameters:
    - title: Provide information about the GitHub location
      required:
        - orgName
        - repoName
        - owner
        - system
      properties:
        orgName:
          title: Organization Name
          type: string
        owner:
          title: Owner
          type: string
          description: Owner of the component
        repoName:
          title: Repository Name
          type: string
        system:
          title: System
          type: string
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind:
                - System
    - title: Ansible Job Definition
      required:
        - name
        - jobTemplate
        - description
        - namespace
      properties:
        name:
          title: Name of the Ansible Job
          type: string
          description: A unique name for the Ansible Job
        jobTemplate:
          title: Name of the Job Template to launch
          type: string
          description: Specify a job template to launch
        description:
          title: Description
          type: string
          description: Provide a description of the Job to be launched
        namespace:
          title: Namespace
          type: string
          description: Specify the namespace to launch the job
          default: aap
        connection_secret:
          title: Connection Secret
          type: string
          description: Specify the connection secret to use for the job
          default: aapaccess
        extra_vars:
          title: Extra Vars
          type: string
          description: Specify any extra vars to pass to the job
          default: {}
          ui:widget: textarea
          ui:options:
            rows: 15
  steps:
    - id: template
      name: Generating the source code component
      action: fetch:template
      input:
        url: ./skeleton
        targetPath: argo/ansibleJobs/
        values:
          component_id: ${{ parameters.name }}
          jobTemplate: ${{ parameters.jobTemplate }}
          name: ${{ parameters.name }}
          namespace: ${{ parameters.namespace }}
          connection_secret: ${{ parameters.connection_secret }}
          extra_vars: ${{ parameters.extra_vars }}

    - id: catalogTemplate
      name: Generating the Catalog Info Component
      action: fetch:template
      input:
        url: ../../../skeletons/catalog-info/
        values:
          orgName: ${{ parameters.orgName }}
          repoName: ${{ parameters.repoName }}
          owner: ${{ parameters.owner }}
          applicationType: api
          description: ${{ parameters.description }}
          sourceControl: github.com

    - id: publish
      name: Publishing to Source Code Repository
      action: publish:github:pull-request
      input:
        allowedHosts: ['github.com']
        title: ${{ parameters.name }}-job
        description: ${{ parameters.name }}-job
        repoUrl: github.com?owner=${{ parameters.orgName }}&repo=${{ parameters.repoName }}
        branchName: ${{ parameters.name }}-job

    - id: register
      name: Registering the Catalog Info Component
      action: catalog:register
      input:
        repoContentsUrl:  https://github.com/${{ parameters.githubOrg }}/${{ parameters.repoName }}/blob/${{ steps.publish.output.targetBranchName }}
        catalogInfoPath: /catalog-info.yaml
        optional: true

  output:
    links:
      - title: Source Code Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open the Catalog Info Component
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
